### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by chandu0211** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#14]
Hello Sir, 
  While running the project I'm getting the following warnings and errors.
![warning](https://user-images.githubusercontent.com/46132286/60683731-fef1b280-9eb6-11e9-8091-ef0da8c9e306.jpg)
![error](https://user-images.githubusercontent.com/46132286/60683734-01540c80-9eb7-11e9-8236-ecc287b0c8c6.jpg)

**Comment by ShreyAmbesh** [comment]
The Warning will not be there if you compile the tensorflow on your machine instead of installing it directly.
Compiling on your machine will help you to use the full capability of your machine.
The error is because of too many requests being sent to the openalpr API. This can be fixed by scheduling all the request at particular intervals and using a queue or eliminating the openalpr and making your own custom solution for detecting License Plate and License Plate Number.
